owner: la-test
repo: sbx1-upptime

sites:
  - name: Least Authority - website
    url: https://leastauthority.com/
    __dangerous__body_degraded_if_text_missing: '<title>Home | Least Authority - Privacy Matters</title>'
    maxRedirects: 0

  - name: Least Authority - redirect
    url: http://leastauthority.com/
    __dangerous__body_degraded_if_text_missing: '<title>Home | Least Authority - Privacy Matters</title>'
    maxRedirects: 1

  - name: Winden - website
    url: https://winden.app/
    __dangerous__body_degraded_if_text_missing: '<title>Winden - secure, fast and easy file transfer'
    maxRedirects: 0

  - name: Winden - redirect
    url: http://winden.app/
    __dangerous__body_degraded_if_text_missing: '<title>Winden - secure, fast and easy file transfer'
    maxRedirects: 1

  - name: Winden - it redirect
    url: http://winden.it/
    __dangerous__body_degraded_if_text_missing: '<title>Winden - secure, fast and easy file transfer'
    maxRedirects: 2

  - name: Winden - me redirect
    url: http://winden.me/
    __dangerous__body_degraded_if_text_missing: '<title>Winden - secure, fast and easy file transfer'
    maxRedirects: 2

  - name: Winden - tech redirect
    url: http://winden.tech/
    __dangerous__body_degraded_if_text_missing: '<title>Winden - secure, fast and easy file transfer'
    maxRedirects: 2

  - name: Private Storage - website
    url: https://private.storage/
    __dangerous__body_degraded_if_text_missing: '<title>PrivateStorage | Private &amp; Secure Cloud Storage</title>'
    maxRedirects: 0

  - name: Private Storage - redirect
    url: http://private.storage/
    __dangerous__body_degraded_if_text_missing: '<title>PrivateStorage | Private &amp; Secure Cloud Storage</title>'
    maxRedirects: 1

  - name: Private Storage - app redirect
    url: http://privatestorage.app/
    __dangerous__body_degraded_if_text_missing: '<title>PrivateStorage | Private &amp; Secure Cloud Storage</title>'
    maxRedirects: 1
    verbose: true

  - name: Private Storage - dev redirect
    url: http://privatestorage.dev/
    __dangerous__body_degraded_if_text_missing: '<title>PrivateStorage | Private &amp; Secure Cloud Storage</title>'
    maxRedirects: 1
    verbose: true

  - name: Private Storage - io redirect
    url: http://privatestorage.io/
    __dangerous__body_degraded_if_text_missing: '<title>PrivateStorage | Private &amp; Secure Cloud Storage</title>'
    maxRedirects: 2

  - name: Private Storage - online redirect
    url: http://privatestorage.online/
    __dangerous__body_degraded_if_text_missing: '<title>PrivateStorage | Private &amp; Secure Cloud Storage</title>'
    maxRedirects: 1

  - name: Private Storage - org redirect
    url: http://privatestorage.org/
    __dangerous__body_degraded_if_text_missing: '<title>PrivateStorage | Private &amp; Secure Cloud Storage</title>'
    maxRedirects: 1
    verbose: true

  - name: Private Storage - tech redirect
    url: http://privatestorage.tech/
    __dangerous__body_degraded_if_text_missing: '<title>PrivateStorage | Private &amp; Secure Cloud Storage</title>'
    maxRedirects: 1
    verbose: true

status-website:
  baseUrl: /sbx1-upptime
  logoUrl: https://raw.githubusercontent.com/la-test/sbx1-upptime/master/assets/upptime-icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by [GitHub](https://github.com/la-test/sbx1-upptime)."
  introMessage: This site monitors the availability of the products and services provided to the end users of [Least Authority](https://leastauthority.com/).
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
